name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: build

          - os: macos-latest
            tasks: >
              iosX64Test
              macosX64Test
              tvosX64Test
              watchosX64Test

          - os: windows-latest
            tasks: mingwX64Test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: build
        run: ./gradlew ${{ matrix.tasks }}


